"""lat lng nas rotas

Revision ID: 11ab76891f9f
Revises: 4e7a58a88db3
Create Date: 2026-06-23 07:27:40.625505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ab76891f9f'
down_revision: Union[str, Sequence[str], None] = '4e7a58a88db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotas', sa.Column('origem_lat', sa.Float(), nullable=True))
    op.add_column('rotas', sa.Column('origem_lng', sa.Float(), nullable=True))
    op.add_column('rotas', sa.Column('destino_lat', sa.Float(), nullable=True))
    op.add_column('rotas', sa.Column('destino_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rotas', 'destino_lng')
    op.drop_column('rotas', 'destino_lat')
    op.drop_column('rotas', 'origem_lng')
    op.drop_column('rotas', 'origem_lat')
    # ### end Alembic commands ###
