"""tabela eventos_auditoria

Revision ID: 4e7a58a88db3
Revises: d813d417a6e6
Create Date: 2026-06-22 23:49:33.280411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7a58a88db3'
down_revision: Union[str, Sequence[str], None] = 'd813d417a6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('detalhe', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_auditoria_created_at'), 'eventos_auditoria', ['created_at'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_id'), 'eventos_auditoria', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_tipo'), 'eventos_auditoria', ['tipo'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_usuario_id'), 'eventos_auditoria', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_auditoria_usuario_id'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_tipo'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_id'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_created_at'), table_name='eventos_auditoria')
    op.drop_table('eventos_auditoria')
    # ### end Alembic commands ###
