"""colunas normalizadas para busca

Revision ID: 81c876e4051c
Revises: 11ab76891f9f
Create Date: 2026-06-23 18:14:00.864728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c876e4051c'
down_revision: Union[str, Sequence[str], None] = '11ab76891f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('rotas', sa.Column('origem_norm', sa.String(), nullable=True))
    op.add_column('rotas', sa.Column('destino_norm', sa.String(), nullable=True))
    op.create_index(op.f('ix_rotas_destino_norm'), 'rotas', ['destino_norm'], unique=False)
    op.create_index(op.f('ix_rotas_origem_norm'), 'rotas', ['origem_norm'], unique=False)

    # Backfill: normaliza origem/destino das rotas já existentes.
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
    from text_utils import normalizar

    conn = op.get_bind()
    rotas = sa.table(
        "rotas",
        sa.column("id", sa.Integer),
        sa.column("origem", sa.String),
        sa.column("destino", sa.String),
        sa.column("origem_norm", sa.String),
        sa.column("destino_norm", sa.String),
    )
    for row in conn.execute(sa.select(rotas.c.id, rotas.c.origem, rotas.c.destino)):
        conn.execute(
            rotas.update()
            .where(rotas.c.id == row.id)
            .values(
                origem_norm=normalizar(row.origem),
                destino_norm=normalizar(row.destino),
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rotas_origem_norm'), table_name='rotas')
    op.drop_index(op.f('ix_rotas_destino_norm'), table_name='rotas')
    op.drop_column('rotas', 'destino_norm')
    op.drop_column('rotas', 'origem_norm')
    # ### end Alembic commands ###
