"""tabela avaliacoes

Revision ID: d813d417a6e6
Revises: 85e987590bfa
Create Date: 2026-06-22 19:35:40.277840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd813d417a6e6'
down_revision: Union[str, Sequence[str], None] = '85e987590bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_id'), 'avaliacoes', ['id'], unique=False)
    op.create_index(op.f('ix_avaliacoes_viagem_id'), 'avaliacoes', ['viagem_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacoes_viagem_id'), table_name='avaliacoes')
    op.drop_index(op.f('ix_avaliacoes_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
